Fix #26: Add liquibase to the docker image
wultra/user-data-store pull request #28
Opened 2023-03-23 08:27 UTC by zcgandcomp

2023-03-23 08:31 UTC, banterCZ commented
Thanks for adding missing indexes and fixing the liquibase at docker. We have to decide what to do with https://github.com/wultra/user-data-store/blob/develop/docs/sql/postgresql/create-schema.sql It should be deleted or updated.

2023-03-23 08:42 UTC, zcgandcomp commented
Regarding create-schema.sql - just tell me what is expected. My idea was we that going to generate (if needed) the script from the liquibase changesets. Or we can maintain them for now manually and resolve the redundancy later.

2023-03-23 10:38 UTC, banterCZ commented
> Or we can maintain them for now manually and resolve the redundancy later.
Ok, we may resolve concept in another PR, but let's edit the script manually to keep it in sync.

2023-03-23 10:40 UTC, banterCZ requested changes

2023-03-23 10:40 UTC, banterCZ commented on docs/db/changelog/changesets/user-data-store/0.1.x/20230322-audit-indexes.xml
> +        <comment>Create indexes on table audit_log and audit_param</comment>
Missing `exists precondition`. Moreover, each index should be extra changeset. See https://github.com/wultra/enrollment-server/blob/develop/docs/db/changelog/changesets/enrollment-server/1.4.x/20230314-audit.xml

2023-03-24 06:09 UTC, banterCZ commented on docs/db/changelog/changesets/user-data-store/0.1.x/20230322-audit-indexes.xml
> +    <changeSet id="`" logicalFilePath="user-data-store/0.1.x/20230322-audit-indexes.xml" author="Lubos Racansky">
```suggestion
    <changeSet id="1" logicalFilePath="user-data-store/0.1.x/20230322-audit-indexes.xml" author="Lubos Racansky">
```

2023-03-24 06:09 UTC, banterCZ commented on docs/db/changelog/changesets/user-data-store/0.1.x/20230322-audit-indexes.xml
> +    <changeSet id="1" logicalFilePath="user-data-store/0.1.x/20230322-audit-indexes.xml" author="Lubos Racansky">
```suggestion
    <changeSet id="2" logicalFilePath="user-data-store/0.1.x/20230322-audit-indexes.xml" author="Lubos Racansky">
```

2023-03-24 07:41 UTC, banterCZ approved these changes

2023-03-24 07:51 UTC, merged