Fix #29: Improve documentation of master encryption key
wultra/user-data-store pull request #30
Opened 2023-03-24 06:26 UTC by banterCZ

2023-03-24 07:33 UTC, zcgandcomp requested changes

2023-03-24 07:33 UTC, zcgandcomp commented on docs/Configuration-Properties.md
> +| `user-data-store.db.master.encryption.key` | `_empty_` | Master DB encryption key (AES-256) to derive server private keys for the encryption of sensitive data in the database. An empty value means
The value has to be in Base64, right? Worth mentioning here.

2023-03-27 16:09 UTC, romanstrobl approved these changes
Looks good, however if we already want to be so specific we can also mention the expected key length for AES-256?

2023-03-28 13:22 UTC, zcgandcomp approved these changes
Looks OK.

2023-03-29 05:00 UTC, merged